
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author marcela
 */
public class lab extends javax.swing.JFrame {

    /**
     * Creates new form lab
     */
    public lab() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialog_Agregar = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTextField_CrearPoder = new javax.swing.JTextField();
        JTextField_CrearNombre = new javax.swing.JTextField();
        JTextField_CrearDebilidad = new javax.swing.JTextField();
        JTextField_CrearFuerza = new javax.swing.JTextField();
        JTextField_AFisica = new javax.swing.JTextField();
        JTextField_CrearAMental = new javax.swing.JTextField();
        JTextField_CrearPuntosVida = new javax.swing.JTextField();
        JButton_Crear = new javax.swing.JButton();
        JComboBox_Universo = new javax.swing.JComboBox<>();
        JDialog_Listar = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree_Arbol = new javax.swing.JTree();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JList_MostrarPersonaje = new javax.swing.JList<>();
        JTextField_NombreListar = new javax.swing.JTextField();
        JDialog_Simular = new javax.swing.JDialog();
        JComboBox_Universo1 = new javax.swing.JComboBox<>();
        JComboBox_Universo2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        JList_PrimerSuperheroe = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        JList_SegundoSuperHeroe = new javax.swing.JList<>();
        JButton_Seleccionar = new javax.swing.JButton();
        JPopUpMenu_Crud = new javax.swing.JPopupMenu();
        JMenuItem_Modificar = new javax.swing.JMenuItem();
        JMenuItem_Eliminar = new javax.swing.JMenuItem();
        JDialog_Modificar = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JTextField_ModificarNombre = new javax.swing.JTextField();
        JTextField_ModificarPoder = new javax.swing.JTextField();
        JTextField_ModificarDebilidad = new javax.swing.JTextField();
        JTextField_ModificarFuerza = new javax.swing.JTextField();
        JTextField_ModificarAFisica = new javax.swing.JTextField();
        JTextField_ModificarAMental = new javax.swing.JTextField();
        JTextField_ModificarPuntosVida = new javax.swing.JTextField();
        JComboBox_ModificarUniverso = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        JButton_Agregar = new javax.swing.JButton();
        JButton_Listar = new javax.swing.JButton();
        JButton_Simular = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu_Agregar = new javax.swing.JMenu();
        JMenu_Listar = new javax.swing.JMenu();
        JMenu_Simulacion = new javax.swing.JMenu();

        JDialog_Agregar.setPreferredSize(new java.awt.Dimension(695, 656));
        JDialog_Agregar.setResizable(false);
        JDialog_Agregar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Autography", 1, 48)); // NOI18N
        jLabel1.setText("Crear");
        JDialog_Agregar.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 15, 91, -1));

        jLabel2.setText("Ingrese el nombre: ");
        JDialog_Agregar.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 95, -1, -1));

        jLabel3.setText("Ingrese el poder: ");
        JDialog_Agregar.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 133, -1, -1));

        jLabel4.setText("Ingrese la debilidad: ");
        JDialog_Agregar.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 174, -1, -1));

        jLabel5.setText("Ingrese el universo: ");
        JDialog_Agregar.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel6.setText("Ingrese la fuerza: ");
        JDialog_Agregar.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 290, -1, -1));

        jLabel7.setText("Ingrese la agilidad fisica: ");
        JDialog_Agregar.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 344, -1, 26));

        jLabel8.setText("Ingrese la agilidad mental: ");
        JDialog_Agregar.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 401, -1, -1));

        jLabel9.setText("Ingrese los puntos de vida: ");
        JDialog_Agregar.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 450, -1, -1));

        JTextField_CrearPoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_CrearPoderActionPerformed(evt);
            }
        });
        JDialog_Agregar.getContentPane().add(JTextField_CrearPoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 130, 388, -1));

        JTextField_CrearNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_CrearNombreActionPerformed(evt);
            }
        });
        JDialog_Agregar.getContentPane().add(JTextField_CrearNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 89, 388, -1));

        JTextField_CrearDebilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_CrearDebilidadActionPerformed(evt);
            }
        });
        JDialog_Agregar.getContentPane().add(JTextField_CrearDebilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 171, 388, -1));

        JTextField_CrearFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_CrearFuerzaActionPerformed(evt);
            }
        });
        JDialog_Agregar.getContentPane().add(JTextField_CrearFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 284, 185, -1));

        JTextField_AFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_AFisicaActionPerformed(evt);
            }
        });
        JDialog_Agregar.getContentPane().add(JTextField_AFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 346, 159, -1));

        JTextField_CrearAMental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_CrearAMentalActionPerformed(evt);
            }
        });
        JDialog_Agregar.getContentPane().add(JTextField_CrearAMental, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 398, 200, -1));

        JTextField_CrearPuntosVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_CrearPuntosVidaActionPerformed(evt);
            }
        });
        JDialog_Agregar.getContentPane().add(JTextField_CrearPuntosVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 447, 200, -1));

        JButton_Crear.setText("Crear");
        JButton_Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_CrearMouseClicked(evt);
            }
        });
        JButton_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_CrearActionPerformed(evt);
            }
        });
        JDialog_Agregar.getContentPane().add(JButton_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 190, 80));

        JComboBox_Universo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel" }));
        JDialog_Agregar.getContentPane().add(JComboBox_Universo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 100, 30));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("DC");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Marvel");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Capcom");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("MK");
        treeNode1.add(treeNode2);
        JTree_Arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree_Arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTree_ArbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTree_Arbol);

        jLabel10.setFont(new java.awt.Font("American Typewriter", 0, 48)); // NOI18N
        jLabel10.setText("Listar");

        jScrollPane2.setViewportView(JList_MostrarPersonaje);

        JTextField_NombreListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_NombreListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JDialog_ListarLayout = new javax.swing.GroupLayout(JDialog_Listar.getContentPane());
        JDialog_Listar.getContentPane().setLayout(JDialog_ListarLayout);
        JDialog_ListarLayout.setHorizontalGroup(
            JDialog_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_ListarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JDialog_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialog_ListarLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(JDialog_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextField_NombreListar, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JDialog_ListarLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel10)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        JDialog_ListarLayout.setVerticalGroup(
            JDialog_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_ListarLayout.createSequentialGroup()
                .addGroup(JDialog_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialog_ListarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JDialog_ListarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextField_NombreListar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        JComboBox_Universo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "MK" }));
        JComboBox_Universo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox_Universo1ActionPerformed(evt);
            }
        });

        JComboBox_Universo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "MK" }));

        jScrollPane3.setViewportView(JList_PrimerSuperheroe);

        jScrollPane4.setViewportView(JList_SegundoSuperHeroe);

        JButton_Seleccionar.setText("Seleccionar");
        JButton_Seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_SeleccionarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JDialog_SimularLayout = new javax.swing.GroupLayout(JDialog_Simular.getContentPane());
        JDialog_Simular.getContentPane().setLayout(JDialog_SimularLayout);
        JDialog_SimularLayout.setHorizontalGroup(
            JDialog_SimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_SimularLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(JDialog_SimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboBox_Universo1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(JButton_Seleccionar)
                .addGap(18, 18, 18)
                .addGroup(JDialog_SimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JComboBox_Universo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addGap(112, 112, 112))
        );
        JDialog_SimularLayout.setVerticalGroup(
            JDialog_SimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_SimularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JDialog_SimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JComboBox_Universo1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboBox_Universo2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JDialog_SimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialog_SimularLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(JDialog_SimularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JDialog_SimularLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(JButton_Seleccionar)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        JMenuItem_Modificar.setText("Modificar");
        JMenuItem_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_ModificarActionPerformed(evt);
            }
        });
        JPopUpMenu_Crud.add(JMenuItem_Modificar);

        JMenuItem_Eliminar.setText("Eliminar");
        JMenuItem_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_EliminarActionPerformed(evt);
            }
        });
        JPopUpMenu_Crud.add(JMenuItem_Eliminar);

        jLabel11.setFont(new java.awt.Font("American Typewriter", 0, 36)); // NOI18N
        jLabel11.setText("Modificar");

        jLabel12.setText("Ingrese el nuevo nombre: ");

        jLabel13.setText("Ingrese el nuevo poder: ");

        jLabel14.setText("Ingrese la nueva debilidad:");

        jLabel15.setText("Ingrese el nuevo universo: ");

        jLabel16.setText("Ingrese la nueva fuerza: ");

        jLabel17.setText("Ingrese la nueva agilidad Fisica: ");

        jLabel18.setText("Ingrese la nueva agilidad mental: ");

        jLabel19.setText("Ingrese los puntos de vida: ");

        JComboBox_ModificarUniverso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "CopCorm", "MK" }));

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JDialog_ModificarLayout = new javax.swing.GroupLayout(JDialog_Modificar.getContentPane());
        JDialog_Modificar.getContentPane().setLayout(JDialog_ModificarLayout);
        JDialog_ModificarLayout.setHorizontalGroup(
            JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel11))
                    .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JTextField_ModificarDebilidad))
                                .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(18, 18, 18)
                                    .addComponent(JComboBox_ModificarUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTextField_ModificarFuerza))
                                .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JTextField_ModificarAFisica, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                                    .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JTextField_ModificarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                        .addComponent(JTextField_ModificarPoder))))
                            .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(33, 33, 33)
                                .addComponent(JTextField_ModificarAMental, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTextField_ModificarPuntosVida, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        JDialog_ModificarLayout.setVerticalGroup(
            JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JDialog_ModificarLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JTextField_ModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JTextField_ModificarPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(JTextField_ModificarDebilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(JComboBox_ModificarUniverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(JTextField_ModificarFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(JTextField_ModificarAFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(JTextField_ModificarAMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(JTextField_ModificarPuntosVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JButton_Agregar.setText("Agregar");
        JButton_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_AgregarMouseClicked(evt);
            }
        });
        JButton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(JButton_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 272, 121));

        JButton_Listar.setText("Listar");
        JButton_Listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_ListarMouseClicked(evt);
            }
        });
        getContentPane().add(JButton_Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 272, 146));

        JButton_Simular.setText("Simular");
        JButton_Simular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_SimularMouseClicked(evt);
            }
        });
        getContentPane().add(JButton_Simular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 286, 152));

        JMenu_Agregar.setText("Agregar");
        JMenu_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_AgregarActionPerformed(evt);
            }
        });
        jMenuBar1.add(JMenu_Agregar);

        JMenu_Listar.setText("Listar");
        JMenu_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_ListarActionPerformed(evt);
            }
        });
        jMenuBar1.add(JMenu_Listar);

        JMenu_Simulacion.setText("Simulacion");
        JMenu_Simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_SimulacionActionPerformed(evt);
            }
        });
        jMenuBar1.add(JMenu_Simulacion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_AgregarActionPerformed

    private void JButton_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_AgregarMouseClicked
        // TODO add your handling code here:
        abrir_Dialog(JDialog_Agregar);
    }//GEN-LAST:event_JButton_AgregarMouseClicked

    private void JButton_ListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_ListarMouseClicked
        // TODO add your handling code here:
        abrir_Dialog(JDialog_Listar);
    }//GEN-LAST:event_JButton_ListarMouseClicked

    private void JButton_SimularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_SimularMouseClicked
        // TODO add your handling code here:
        abrir_Dialog(JDialog_Simular);
    }//GEN-LAST:event_JButton_SimularMouseClicked

    private void JMenu_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_AgregarActionPerformed
        // TODO add your handling code here:
        abrir_Dialog(JDialog_Agregar);
    }//GEN-LAST:event_JMenu_AgregarActionPerformed

    private void JMenu_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_ListarActionPerformed
        // TODO add your handling code here:
        abrir_Dialog(JDialog_Listar);
    }//GEN-LAST:event_JMenu_ListarActionPerformed

    private void JMenu_SimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_SimulacionActionPerformed
        // TODO add your handling code here:
        abrir_Dialog(JDialog_Simular);
    }//GEN-LAST:event_JMenu_SimulacionActionPerformed

    private void JTextField_CrearPoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_CrearPoderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_CrearPoderActionPerformed

    private void JTextField_CrearNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_CrearNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_CrearNombreActionPerformed

    private void JTextField_CrearDebilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_CrearDebilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_CrearDebilidadActionPerformed

    private void JTextField_CrearFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_CrearFuerzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_CrearFuerzaActionPerformed

    private void JTextField_AFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_AFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_AFisicaActionPerformed

    private void JTextField_CrearAMentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_CrearAMentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_CrearAMentalActionPerformed

    private void JTextField_CrearPuntosVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_CrearPuntosVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_CrearPuntosVidaActionPerformed

    private void JButton_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_CrearActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JButton_CrearActionPerformed

    private void JButton_CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_CrearMouseClicked
        // TODO add your handling code here:

        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) JComboBox_Universo.getModel();
        modelo.addElement("DC");
        modelo.addElement("Marvel");
        JComboBox_Universo.setModel(modelo);

        int existe = -1;

        DefaultTreeModel m = (DefaultTreeModel) JTree_Arbol.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_personaje;
        nodo_personaje = new DefaultMutableTreeNode(new Personaje(JTextField_CrearNombre.getText(), JTextField_CrearPoder.getText(), JTextField_CrearDebilidad.getText(), JComboBox_Universo.getSelectedItem().toString(), Integer.parseInt(JTextField_CrearFuerza.getText()), Integer.parseInt(JTextField_AFisica.getText()), Integer.parseInt(JTextField_CrearAMental.getText()), Integer.parseInt(JTextField_CrearPuntosVida.getText()), true));
        personajes.add(new Personaje(JTextField_CrearNombre.getText(), JTextField_CrearPoder.getText(), JTextField_CrearDebilidad.getText(), JComboBox_Universo.getSelectedItem().toString(), Integer.parseInt(JTextField_CrearFuerza.getText()), Integer.parseInt(JTextField_AFisica.getText()), Integer.parseInt(JTextField_CrearAMental.getText()), Integer.parseInt(JTextField_CrearPuntosVida.getText()), true));
       
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().
                    equals(JComboBox_Universo.getSelectedItem().toString())) {
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(new Personaje(JTextField_CrearNombre.getText(), JTextField_CrearPoder.getText(), JTextField_CrearDebilidad.getText(), JComboBox_Universo.getSelectedItem().toString(), Integer.parseInt(JTextField_CrearFuerza.getText()), Integer.parseInt(JTextField_AFisica.getText()), Integer.parseInt(JTextField_CrearAMental.getText()), Integer.parseInt(JTextField_CrearPuntosVida.getText()), true));

                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                existe = 1;
            } //fin if
        } //fin for 
        if (existe == -1) {
            JOptionPane.showMessageDialog(JDialog_Agregar, "Ingrese un superheroe dentro de los universos estipulados");
        }
        
         for (int i = 0; i < personajes.size(); i++) {
            if (personajes.get(i).getUniverso().equals("DC")) {
                dc.add(personajes.get(i));
            }else if (personajes.get(i).getUniverso().equals("Marvel")) {
                Marvel.add(personajes.get(i));
            }else if (personajes.get(i).getUniverso().equals("Capcom")) {
                capcom.add(personajes.get(i));
            }else if (personajes.get(i).getUniverso().equals("MK")) {
                MK.add(personajes.get(i));
            }
        }

//        DefaultMutableTreeNode nodo_universo;
//        nodo_universo = new DefaultMutableTreeNode(JComboBox_Universo.getSelectedItem().toString());
//        if (existe == -1) {
//                DefaultMutableTreeNode n
//                        = new DefaultMutableTreeNode(JComboBox_Universo.getSelectedItem().toString());
//                DefaultMutableTreeNode p
//                        = new DefaultMutableTreeNode(
//                                JComboBox_Universo.getSelectedItem().toString());
//                n.add(p);
//                raiz.add(n);
//            }  // fin if          
//            m.reload();
//        nodo_universo.add(nodo_personaje);
//        raiz.add(nodo_universo);
//        m.reload();
        JDialog_Agregar.setVisible(false);
    }//GEN-LAST:event_JButton_CrearMouseClicked

    private void JTree_ArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTree_ArbolMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            //seleccionar un nodo con click derecho
            int row = JTree_Arbol.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            JTree_Arbol.setSelectionRow(row);
            Object v1
                    = JTree_Arbol.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            
            if (nodo_seleccionado.getUserObject() instanceof Personaje) {
                personaje_seleccionada
                        = (Personaje) nodo_seleccionado.
                                getUserObject();
                JPopUpMenu_Crud.show(evt.getComponent(),
                        evt.getX(), evt.getY());
                JTextField_NombreListar.setText(nodo_seleccionado.toString());
                list.removeAllElements();
                for (Personaje personaje : personajes) {
                    personaje.setS(false);
                    list.addElement(personaje);
                    JList_MostrarPersonaje.setModel(list);
                }

            }else {
                JOptionPane.showMessageDialog(JDialog_Listar, "Seleccione alguien");
            }

        }
    }//GEN-LAST:event_JTree_ArbolMouseClicked

    private void JMenuItem_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_ModificarActionPerformed
        // TODO add your handling code here:
        abrir_Dialog(JDialog_Modificar);

    }//GEN-LAST:event_JMenuItem_ModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        DefaultTreeModel m
                = (DefaultTreeModel) JTree_Arbol.getModel();

        personaje_seleccionada.setNombre(
                JTextField_ModificarNombre.getText());
        personaje_seleccionada.setPoder(
                JTextField_ModificarPoder.getText());
        personaje_seleccionada.setDebilidad(
                JTextField_ModificarDebilidad.getText());
        personaje_seleccionada.setUniverso(
                JComboBox_ModificarUniverso.getSelectedItem().toString());
        personaje_seleccionada.setFuerza(
                Integer.parseInt(JTextField_ModificarFuerza.getText()));
        personaje_seleccionada.setAgilidadFisica(
                Integer.parseInt(JTextField_ModificarAFisica.getText()));
        personaje_seleccionada.setAgilidadMental(
                Integer.parseInt(JTextField_ModificarAMental.getText()));
        personaje_seleccionada.setPuntosdeVida(
                Integer.parseInt(JTextField_ModificarPuntosVida.getText()));

        m.reload();

        JDialog_Modificar.setVisible(false);
        abrir_Dialog(JDialog_Listar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JMenuItem_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_EliminarActionPerformed
        // TODO add your handling code here:

        DefaultTreeModel m
                = (DefaultTreeModel) JTree_Arbol.getModel();
        m.removeNodeFromParent(
                nodo_seleccionado);
        m.reload();

        JOptionPane.showMessageDialog(JDialog_Listar, "Eliminado con exito");

    }//GEN-LAST:event_JMenuItem_EliminarActionPerformed

    private void JTextField_NombreListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_NombreListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField_NombreListarActionPerformed

    private void JComboBox_Universo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBox_Universo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBox_Universo1ActionPerformed

    private void JButton_SeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_SeleccionarMouseClicked
        // TODO add your handling code here:
        Personaje personaje1;
        Personaje personaje2;
        if (JComboBox_Universo1.getSelectedItem().equals("DC")) {
            System.out.println(dc.toString());
            DefaultListModel modeloLISTA
                    = (DefaultListModel) JList_PrimerSuperheroe.getModel();
            personaje1 = (Personaje) modeloLISTA.get(JList_PrimerSuperheroe.getSelectedIndex());
        }
        
    }//GEN-LAST:event_JButton_SeleccionarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Agregar;
    private javax.swing.JButton JButton_Crear;
    private javax.swing.JButton JButton_Listar;
    private javax.swing.JButton JButton_Seleccionar;
    private javax.swing.JButton JButton_Simular;
    private javax.swing.JComboBox<String> JComboBox_ModificarUniverso;
    private javax.swing.JComboBox<String> JComboBox_Universo;
    private javax.swing.JComboBox<String> JComboBox_Universo1;
    private javax.swing.JComboBox<String> JComboBox_Universo2;
    private javax.swing.JDialog JDialog_Agregar;
    private javax.swing.JDialog JDialog_Listar;
    private javax.swing.JDialog JDialog_Modificar;
    private javax.swing.JDialog JDialog_Simular;
    private javax.swing.JList<String> JList_MostrarPersonaje;
    private javax.swing.JList<String> JList_PrimerSuperheroe;
    private javax.swing.JList<String> JList_SegundoSuperHeroe;
    private javax.swing.JMenuItem JMenuItem_Eliminar;
    private javax.swing.JMenuItem JMenuItem_Modificar;
    private javax.swing.JMenu JMenu_Agregar;
    private javax.swing.JMenu JMenu_Listar;
    private javax.swing.JMenu JMenu_Simulacion;
    private javax.swing.JPopupMenu JPopUpMenu_Crud;
    private javax.swing.JTextField JTextField_AFisica;
    private javax.swing.JTextField JTextField_CrearAMental;
    private javax.swing.JTextField JTextField_CrearDebilidad;
    private javax.swing.JTextField JTextField_CrearFuerza;
    private javax.swing.JTextField JTextField_CrearNombre;
    private javax.swing.JTextField JTextField_CrearPoder;
    private javax.swing.JTextField JTextField_CrearPuntosVida;
    private javax.swing.JTextField JTextField_ModificarAFisica;
    private javax.swing.JTextField JTextField_ModificarAMental;
    private javax.swing.JTextField JTextField_ModificarDebilidad;
    private javax.swing.JTextField JTextField_ModificarFuerza;
    private javax.swing.JTextField JTextField_ModificarNombre;
    private javax.swing.JTextField JTextField_ModificarPoder;
    private javax.swing.JTextField JTextField_ModificarPuntosVida;
    private javax.swing.JTextField JTextField_NombreListar;
    private javax.swing.JTree JTree_Arbol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
    private void abrir_Dialog(JDialog jd) {
        jd.setModal(true);
        jd.pack();
        jd.setLocationRelativeTo(this);
        jd.setVisible(true);
    }

    public void actualizarArbol() {
        DefaultTreeModel m
                = (DefaultTreeModel) JTree_Arbol.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_personaje;
        for (int i = 0; i < personajes.size(); i++) {
            nodo_personaje = new DefaultMutableTreeNode(personajes.get(i));
            switch (personajes.get(i).getUniverso()) {
                case "DC" -> {
                    ((DefaultMutableTreeNode) raiz.getChildAt(0)).add(nodo_personaje);
                }
                case "Marvel" -> {
                    ((DefaultMutableTreeNode) raiz.getChildAt(1)).add(nodo_personaje);
                }
                case "Capcom" -> {
                    ((DefaultMutableTreeNode) raiz.getChildAt(2)).add(nodo_personaje);
                }
                case "MK" -> {
                    ((DefaultMutableTreeNode) raiz.getChildAt(3)).add(nodo_personaje);
                }
            }
        }
    }

 
    ArrayList<Personaje> personajes = new ArrayList();
    ArrayList<Personaje> dc = new ArrayList();
    ArrayList<Personaje> Marvel = new ArrayList();
    ArrayList<Personaje> capcom = new ArrayList();
    ArrayList<Personaje> MK = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Personaje personaje_seleccionada;
    DefaultListModel list = new DefaultListModel();
}
